# Generated by Django 3.0.9 on 2020-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
