# Generated by Django 3.1.2 on 2020-10-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_maths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('correct_answers', models.IntegerField()),
                ('wrong_answers', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Question',
            new_name='Programming',
        ),
    ]
